# # config file version
apiVersion: 1
datasources:
- name: influxdb
  # <string, required> datasource type. Required
  type: influxdb
  # <string, required> access mode. direct or proxy. Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: http://influxdb:8086
  database: krakend
  # <string> database password, if used
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true

- name: opencensus
  # <string, required> datasource type. Required
  type: influxdb
  # <string, required> access mode. direct or proxy. Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: http://influxdb:8086
  database: opencensus
  # <string> database password, if used
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true

# # list of datasources that should be deleted from the database
#deleteDatasources:
#   - name: Graphite
#     orgId: 1


